name: Microservice Brewery Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven and Verify
        run: mvn --batch-mode --update-snapshots verify
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
